name: ui_clinic_business
description: "Proyecto de la clinica PROCMEFA - Interfaz de usuario de escritorio, movi"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  window_manager: ^0.5.1
  responsive_builder: ^0.7.1 # <-- agregado aquí

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
